### PR TITLE
add batch `revoke` and `forgive` functions

### PR DESCRIPTION
**Pull request by spengrah**
This PR adds batch versions of the `revoke` and `forgive` functions. The new functions overload the same function names but take arrays of addresses instead of a single address.

### CODE REVIEW

**Comment by gershido** [comment]
Nice! two thoughts:
1. Suggestion for a small gas optimization, adding a `hatId` param for the `_forgive` and `_revoke` functions. This will save extra `hatId()` calls when using the batched functions. 
2. What do you think about adding events for the `forgive` and `revoke` actions? This will make indexing much simpler

**Comment by spengrah** [comment]
> 1. Suggestion for a small gas optimization, adding a `hatId` param for the `_forgive` and `_revoke` functions. This will save extra `hatId()` calls when using the batched functions.

good suggestion, added

> 2. What do you think about adding events for the `forgive` and `revoke` actions? This will make indexing much simpler

@gershido, could do. What specifically do you want logged? If you want the standing status change, can you not get that from `Hats.WearerStandingChanged`?

**Comment by gershido** [comment]
We currently do get that from `Hats.WearerStandingChanged` but it's tricky. We need to listen to this event from Hats.sol and then check if the event was triggered from a hat which eligibility address is an agreement eligibility module. That's not too bad but then, if it's from a chain you potentially wouldn't be able to know which module triggered a wearer status change without calling the module contract to see the status of the wearer there.

**Comment by spengrah** [comment]
> We currently do get that from `Hats.WearerStandingChanged` but it's tricky. We need to listen to this event from Hats.sol and then check if the event was triggered from a hat which eligibility address is an agreement eligibility module. That's not too bad but then, if it's from a chain you potentially wouldn't be able to know which module triggered a wearer status change without calling the module contract to see the status of the wearer there.

And what's the reason we need to know which module triggered a wearer status change?

**Comment by gershido** [comment]
If we want the UI to display that a wearer was put into bad standing particularly in the agreement eligibility (or other module)

**Comment by spengrah** [comment]
> If we want the UI to display that a wearer was put into bad standing particularly in the agreement eligibility (or other module)

@scottrepreneur is this relevant to the current (or future plausible) designs?

**Comment by spengrah** [comment]
would we want both `wearer` and `hatId` logged, or is the latter redundant?

**Comment by gershido** [comment]
`wearer` will be enough (because `hatId` is constant in the module)

**Comment by spengrah** [comment]
FYI including the events adds between 500-1000 gas for individual revoke and forgive calls

**Review by gershido — APPROVED** [review]

**Pull request merged**
